"""Train the EvidenceGNN refiner for tree parsing.

Loads pre-computed evidence from .pt files (generated by gen_data.py).

Usage:
    python3.10 tree_parser/gnn/train.py --subset-run mixed_v8 --train-data train --val-data val --run mixed_v8
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

from mathnote_ocr.engine.checkpoint import _checkpoint_path, save_checkpoint
from mathnote_ocr.tree_parser.gnn.dataset import GNNDataset, collate_fn
from mathnote_ocr.tree_parser.gnn.model import EvidenceGNN

log = logging.getLogger(__name__)

# Repo-root data/runs/gnn/. Parents: gnn → tree_parser → mathnote_ocr → src → repo-root.
DATA_DIR = Path(__file__).resolve().parents[4] / "data" / "runs" / "gnn"


# ── Loss computation ─────────────────────────────────────────────────


def compute_loss(
    out: dict[str, torch.Tensor],
    gt_parent: torch.Tensor,  # (B, N)
    gt_edge_type: torch.Tensor,  # (B, N)
    gt_seq: torch.Tensor,  # (B, N)
    pad_mask: torch.Tensor,  # (B, N)
) -> tuple[torch.Tensor, dict[str, float]]:
    """Compute parent + edge type + seq loss."""
    B, N = gt_parent.shape
    device = gt_parent.device

    parent_scores = out["parent_scores"]  # (B, N, N+1)
    edge_type_scores = out["edge_type_scores"]  # (B, N, N+1, E)
    seq_scores = out["seq_scores"]  # (B, N, N+1)

    # Parent loss: CE over N+1 classes
    parent_loss = nn.functional.cross_entropy(
        parent_scores.view(-1, N + 1),
        gt_parent.view(-1),
        ignore_index=-100,
    )

    # SEQ loss: CE over N+1 classes
    seq_loss = nn.functional.cross_entropy(
        seq_scores.view(-1, N + 1),
        gt_seq.view(-1),
        ignore_index=-100,
    )

    # Valid masks
    valid_all = (~pad_mask) & (gt_parent != -100)
    valid_edge = valid_all & (gt_edge_type != -100)

    # Edge type loss: CE for structural children (not ROOT children)
    if valid_edge.any():
        eidx = valid_edge.nonzero(as_tuple=False)
        eb, es = eidx[:, 0], eidx[:, 1]
        ep = gt_parent[eb, es]
        edge_logits = edge_type_scores[eb, es, ep]  # (Ve, E)
        edge_tgt = gt_edge_type[eb, es]
        edge_loss = nn.functional.cross_entropy(edge_logits, edge_tgt)

        with torch.no_grad():
            edge_pred = edge_logits.argmax(dim=-1)
            edge_acc = (edge_pred == edge_tgt).float().mean().item()
    else:
        edge_loss = torch.tensor(0.0, device=device)
        edge_acc = 0.0

    # Parent accuracy
    if valid_all.any():
        with torch.no_grad():
            aidx = valid_all.nonzero(as_tuple=False)
            ab, a_s = aidx[:, 0], aidx[:, 1]
            ap = gt_parent[ab, a_s]
            parent_pred = parent_scores[ab, a_s].argmax(dim=-1)
            parent_acc = (parent_pred == ap).float().mean().item()
    else:
        parent_acc = 0.0

    # SEQ accuracy
    valid_seq = (~pad_mask) & (gt_seq != -100)
    if valid_seq.any():
        with torch.no_grad():
            sidx = valid_seq.nonzero(as_tuple=False)
            sb, ss = sidx[:, 0], sidx[:, 1]
            seq_pred = seq_scores[sb, ss].argmax(dim=-1)
            seq_acc = (seq_pred == gt_seq[sb, ss]).float().mean().item()
    else:
        seq_acc = 0.0

    loss = parent_loss + edge_loss + seq_loss

    metrics = {
        "parent_loss": parent_loss.item(),
        "edge_loss": edge_loss.item(),
        "seq_loss": seq_loss.item(),
        "parent_acc": parent_acc,
        "edge_acc": edge_acc,
        "seq_acc": seq_acc,
    }
    return loss, metrics


# ── Training ─────────────────────────────────────────────────────────


def _default_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def train(
    run: str,
    subset_run: str,
    train_data: str,
    val_data: str,
    device: torch.device | None = None,
    *,
    weights_dir: str | Path | None = None,
    epochs: int = 50,
    batch_size: int = 32,
    lr: float = 1e-3,
    dropout: float = 0.1,
    d_model: int = 64,
    n_heads: int = 4,
    n_layers: int = 3,
    d_ff: int = 128,
    d_edge: int = 11,
    d_arc: int = 32,
    sparse_attention: bool = False,
    resume: bool = False,
) -> Path:
    """Train an EvidenceGNN model.

    Args:
        run: Run name (checkpoint saved to ``{weights_dir}/tree_gnn/{run}/``).
        subset_run: Subset model run name (subdir under data/runs/gnn/).
        train_data: Name of train .pt file (without extension).
        val_data: Name of val .pt file (without extension).
        device: Torch device (auto-detected if None).
        weights_dir: Directory to save weights under. Defaults to the
            bundled package weights dir — CLI callers should pass
            ``./weights``.

    Returns:
        Path to the checkpoint directory.
    """
    if device is None:
        device = _default_device()

    run_dir = _checkpoint_path("tree_gnn", run, weights_dir=weights_dir).parent
    run_dir.mkdir(parents=True, exist_ok=True)

    log_path = run_dir / "train.log"
    fh = logging.FileHandler(log_path, mode="a")
    fh.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s", datefmt="%H:%M:%S"))
    log.addHandler(fh)

    log.info("Run:        %s", run)
    log.info("Subset run: %s", subset_run)
    log.info("Train data: %s", train_data)
    log.info("Val data:   %s", val_data)
    log.info("Device:     %s", device)

    # Load pre-computed datasets
    train_pt = DATA_DIR / subset_run / f"{train_data}.pt"
    val_pt = DATA_DIR / subset_run / f"{val_data}.pt"

    log.info("Loading train dataset from %s...", train_pt)
    train_ds = GNNDataset.from_file(train_pt)
    log.info("Loading val dataset from %s...", val_pt)
    val_ds = GNNDataset.from_file(val_pt)

    # Get symbol_vocab from train data
    train_meta = torch.load(train_pt, map_location="cpu", weights_only=False)
    symbol_vocab = train_meta["symbol_vocab"]
    num_symbols = len(symbol_vocab)
    log.info("  vocab=%d symbols", num_symbols)

    train_loader = DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=True,
        collate_fn=collate_fn,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        pin_memory=True,
        collate_fn=collate_fn,
    )

    # GNN model
    best_val_loss = float("inf")
    best_state = None
    best_epoch = 0
    start_epoch = 1

    if resume:
        ckpt_path = run_dir / "checkpoint.pth"
        if ckpt_path.exists():
            ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
            cfg = ckpt["config"]
            model = EvidenceGNN(**cfg).to(device)
            model.load_state_dict(ckpt["model_state_dict"])
            start_epoch = ckpt.get("epoch", 0) + 1
            best_val_loss = ckpt.get("best_val_loss", float("inf"))
            log.info("Resumed from epoch %d", start_epoch - 1)
        else:
            model = None
    else:
        model = None

    if model is None:
        model = EvidenceGNN(
            num_symbols=num_symbols,
            d_model=d_model,
            n_heads=n_heads,
            n_layers=n_layers,
            d_ff=d_ff,
            d_edge=d_edge,
            d_arc=d_arc,
            dropout=dropout,
            sparse_attention=sparse_attention,
        ).to(device)

    total_params = sum(p.numel() for p in model.parameters())
    log.info("Model parameters: %s", f"{total_params:,}")

    # Optimizer
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=epochs,
        eta_min=1e-5,
    )

    use_amp = device.type == "cuda"
    scaler = torch.amp.GradScaler(enabled=use_amp)
    amp_ctx = lambda: torch.autocast("cuda", dtype=torch.float16, enabled=use_amp)

    meta_subset_run = train_meta.get("subset_run", "unknown")

    # Save run config
    run_config = {
        "subset_run": meta_subset_run,
        "train_data": train_data,
        "val_data": val_data,
        "d_model": d_model,
        "n_heads": n_heads,
        "n_layers": n_layers,
        "d_ff": d_ff,
        "d_edge": d_edge,
        "d_arc": d_arc,
        "batch_size": batch_size,
        "lr": lr,
        "epochs": epochs,
        "dropout": dropout,
        "sparse_attention": sparse_attention,
        "started_at": datetime.now(timezone.utc).isoformat(),
    }
    (run_dir / "config.json").write_text(json.dumps(run_config, indent=2) + "\n")

    for epoch in range(start_epoch, start_epoch + epochs):
        t0 = time.time()
        # ── Train ──
        model.train()
        epoch_metrics = {
            k: 0.0
            for k in [
                "parent_loss",
                "edge_loss",
                "seq_loss",
                "parent_acc",
                "edge_acc",
                "seq_acc",
            ]
        }
        n_batches = 0

        for batch in train_loader:
            with amp_ctx():
                out = model(
                    batch["symbol_ids"].to(device),
                    batch["size_feats"].to(device),
                    batch["edge_features"].to(device),
                    batch["pad_mask"].to(device),
                )
                loss, metrics = compute_loss(
                    out,
                    batch["gt_parent"].to(device),
                    batch["gt_edge_type"].to(device),
                    batch["gt_seq"].to(device),
                    batch["pad_mask"].to(device),
                )

            optimizer.zero_grad(set_to_none=True)
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()

            for k, v in metrics.items():
                epoch_metrics[k] += v
            n_batches += 1

        for k in epoch_metrics:
            epoch_metrics[k] /= max(n_batches, 1)

        scheduler.step()

        # ── Validate ──
        model.eval()
        val_metrics = {k: 0.0 for k in epoch_metrics}
        val_batches = 0

        with torch.no_grad():
            for batch in val_loader:
                with amp_ctx():
                    out = model(
                        batch["symbol_ids"].to(device),
                        batch["size_feats"].to(device),
                        batch["edge_features"].to(device),
                        batch["pad_mask"].to(device),
                    )
                    _, metrics = compute_loss(
                        out,
                        batch["gt_parent"].to(device),
                        batch["gt_edge_type"].to(device),
                        batch["gt_seq"].to(device),
                        batch["pad_mask"].to(device),
                    )

                for k, v in metrics.items():
                    val_metrics[k] += v
                val_batches += 1

        for k in val_metrics:
            val_metrics[k] /= max(val_batches, 1)

        val_loss = val_metrics["parent_loss"] + val_metrics["edge_loss"] + val_metrics["seq_loss"]
        cur_lr = optimizer.param_groups[0]["lr"]

        log.info(
            "Epoch %3d/%d  t_par=%.1f%%  t_edge=%.1f%%  t_seq=%.1f%%  "
            "v_par=%.1f%%  v_edge=%.1f%%  v_seq=%.1f%%  v_loss=%.4f  lr=%.2e  (%ds)",
            epoch,
            start_epoch + epochs - 1,
            100 * epoch_metrics["parent_acc"],
            100 * epoch_metrics["edge_acc"],
            100 * epoch_metrics["seq_acc"],
            100 * val_metrics["parent_acc"],
            100 * val_metrics["edge_acc"],
            100 * val_metrics["seq_acc"],
            val_loss,
            cur_lr,
            int(time.time() - t0),
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_epoch = epoch
            best_state = {
                "model_state_dict": {k: v.clone() for k, v in model.state_dict().items()},
                "epoch": epoch,
                "best_val_loss": best_val_loss,
                "symbol_vocab": symbol_vocab,
                "config": {
                    "num_symbols": num_symbols,
                    "d_model": d_model,
                    "n_heads": n_heads,
                    "n_layers": n_layers,
                    "d_ff": d_ff,
                    "d_edge": d_edge,
                    "d_arc": d_arc,
                    "dropout": dropout,
                    "sparse_attention": sparse_attention,
                },
                "metrics": val_metrics,
                "subset_run": meta_subset_run,
            }
            save_checkpoint("tree_gnn", run, best_state, weights_dir=weights_dir)
            log.info("  -> Best (val_loss=%.4f) -> saved", val_loss)

    if best_state is not None:
        run_config["best_epoch"] = best_epoch
        run_config["best_val_loss"] = round(best_val_loss, 6)
        run_config["best_parent_acc"] = round(best_state["metrics"]["parent_acc"], 4)
        run_config["best_edge_acc"] = round(best_state["metrics"]["edge_acc"], 4)
        run_config["best_seq_acc"] = round(best_state["metrics"].get("seq_acc", 0), 4)
        run_config["finished_at"] = datetime.now(timezone.utc).isoformat()
        (run_dir / "config.json").write_text(json.dumps(run_config, indent=2) + "\n")

        log.info("Done. Best val_loss: %.4f (epoch %d)", best_val_loss, best_epoch)
        log.info("  parent_acc: %.1f%%", 100 * best_state["metrics"]["parent_acc"])
        log.info("  edge_acc:   %.1f%%", 100 * best_state["metrics"]["edge_acc"])
        log.info("  seq_acc:    %.1f%%", 100 * best_state["metrics"].get("seq_acc", 0))
        log.info("Checkpoint: %s", run_dir / "checkpoint.pth")
    else:
        log.info("Done. No improvement found.")

    log.info("Log: %s", log_path)
    log.removeHandler(fh)
    fh.close()
    return run_dir


# ── CLI ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
    )

    parser = argparse.ArgumentParser(description="Train EvidenceGNN")

    parser.add_argument(
        "--subset-run", required=True, help="Subset model run (subdir under data/runs/gnn/)"
    )
    parser.add_argument("--train-data", required=True, help="Name of train .pt file")
    parser.add_argument("--val-data", required=True, help="Name of val .pt file")
    parser.add_argument("--run", default="v1")
    parser.add_argument(
        "--weights-dir",
        type=str,
        default="weights",
        help="Directory to save weights (default: ./weights)",
    )
    parser.add_argument("--resume", action="store_true")

    # Training
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--dropout", type=float, default=0.1)

    # Model
    parser.add_argument("--d-model", type=int, default=64)
    parser.add_argument("--n-heads", type=int, default=4)
    parser.add_argument("--n-layers", type=int, default=3)
    parser.add_argument("--d-ff", type=int, default=128)
    parser.add_argument("--d-edge", type=int, default=11)
    parser.add_argument("--d-arc", type=int, default=32)
    parser.add_argument(
        "--sparse-attention", action="store_true", help="Only attend to nodes with evidence votes"
    )

    args = parser.parse_args()

    train(
        run=args.run,
        subset_run=args.subset_run,
        train_data=args.train_data,
        val_data=args.val_data,
        weights_dir=args.weights_dir,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        dropout=args.dropout,
        d_model=args.d_model,
        n_heads=args.n_heads,
        n_layers=args.n_layers,
        d_ff=args.d_ff,
        d_edge=args.d_edge,
        d_arc=args.d_arc,
        sparse_attention=args.sparse_attention,
        resume=args.resume,
    )
